### ISSUE TITLE
Set Temp not shown unless heating

### ISSUE THREAD

**Issue by paullsoucy** [stelpro/Ki-Z-Wave-Thermostat#1]
I have an issue in that the set temperature between the up and down arrow is blank (I didn't know there should be one until I saw a post for the ZigBee thermostat). I have to go to the "Recently" screen to see the set temp. If I increase the temp enough to start the heater, the "Heating to xx" appears and tile changes from Green to Orange. As long as the set temp is calling for heat, I see the "Heating to xx"  temperature but when it is no longer calling for heat, I only know I am in Comfort mode but do not know the set temp

It would be very convenient to have a slide bar to raise and lower the temp rather than hitting an up or down arrow to make the change. I am not typically making a minor adjustment but rather a much larger change when I arrive or depart my cottage.

**Comment by paullsoucy** [comment]
Is there any update on this issue?  At a minimum I would like the same format related to set temp as now available on the Zigbee version released on 07/21/17.

**Comment by stelpro** [comment]
Hi Paul,

There is no plan to add a slider into the device handler.
However, you may get the latest version with the updated Heat setpoint tile.
