### ISSUE TITLE
Basic and Association events

### ISSUE THREAD

**Issue by BrianAker** [stelpro/Ki-Z-Wave-Thermostat#2]
You are declaring the Z-Wave commands that you are accepting. You wrote events for Association and Basic, but your parse method does not declare you can receive them.

def map = createEvent(zwaveEvent(zwave.parse(description, [0x40:2, 0x43:2, 0x31:3, 0x42:1, 0x20:1, 0x85: 2])))

**Comment by stelpro** [comment]
You are right.
Fixed has been made.
However, there is no plan to use the Basic command class in this device handler for now.
