### ISSUE TITLE
Will this work with new Smartthings Android app?

### ISSUE THREAD

**Issue by kevnord** [stelpro/Ki-Z-Wave-Thermostat#3]
Greetings!
I've been using this handler with my ST 2 hub and Android app. Samsung is phasing out the Smartthings app (now called Smartthings Classic) and moving everyone to a new Smartthings app (previous called Samsung Connect). 

Has anyone tried this handler with the new app?

**Comment by stelpro** [comment]
Hi,

It does not work with the new app yet.

**Comment by ppnadeau** [comment]
Just got the update to the new Smartthings app and I can confirm it doesn't work with the latest handler from April.

**Comment by kevnord** [comment]
Thanks for the info @ppnadeau

**Comment by PhilGo20** [comment]
Any update on this? Can i use Ki with Smartthings?

**Comment by jsturess** [comment]
Does it work for Fibaro Heat Controller Temperature Sensor FGBRS-001?
https://shop.zwave.eu/products/heating-and-climate-control/1589/fibaro-heat-controller-thermostat-sensor

**Comment by stelpro** [comment]
As for the Fibaro Heat Controller Temperature Sensor, no test have been done with it.
However keep in mind that the thermostat cannot use a remote sensor to control the temperature.

**Comment by stelpro** [comment]
Yes, you may use the Ki thermostat with the SmartThings hub.
Just be sure to use the "SmartThings Classic" app.

**Comment by TomasTokaMrazek** [comment]
> Does it work for Fibaro Heat Controller Temperature Sensor FGBRS-001?
> https://shop.zwave.eu/products/heating-and-climate-control/1589/fibaro-heat-controller-thermostat-sensor

@jsturess You can use this https://community.smartthings.com/t/release-dth-for-fibaro-heat-controller-fgt-001/122733

DISCLAIMER: It's mine.

**Comment by stelpro** [comment]
The Stelpro Ki Z-Wave thermostat should now be recognized by the SmartThings platform without the use of this custom device handler.
